"""add full text search to quran

Revision ID: 2395bc715d6d
Revises: 08c9cfcf5c1d
Create Date: 2026-08-30 10:53:26.528894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2395bc715d6d'
down_revision: Union[str, Sequence[str], None] = '08c9cfcf5c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran', sa.Column('translation_search', postgresql.TSVECTOR(), nullable=True))
    op.create_index('idx_quran_translation_search', 'quran', ['translation_search'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_quran_translation_search', table_name='quran', postgresql_using='gin')
    op.drop_column('quran', 'translation_search')
    # ### end Alembic commands ###
